# Generated by Django 5.2.6 on 2026-05-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_docters_delete_docter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docters',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
    ]
