# Generated by Django 5.2.6 on 2026-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_docters_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docters',
            options={},
        ),
        migrations.AlterField(
            model_name='docters',
            name='dep_image',
            field=models.ImageField(upload_to='Docters'),
        ),
    ]
