# Generated by Django 5.2.6 on 2026-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_doctor_alter_booking_doc_name_delete_docters'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('09:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM', '11:00 AM - 12:00 PM'), ('02:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM', '03:00 PM - 04:00 PM')], default='09:00 AM', max_length=20),
        ),
    ]
